// Style constants for Customer pages

export const customerStyles = {
    container: "flex h-screen bg-gray-50",
    sidebar: "w-64 bg-white/80 backdrop-blur-md border-r border-black/10 flex flex-col",
    sidebarHeader: "p-6 border-b border-black/10",
    sidebarTitle: "text-xl font-bold text-gray-900",
    sidebarNav: "flex-1 p-4",
    navList: "space-y-2",
    navItem: "block",
    navLink: "flex items-center gap-3 px-4 py-3 rounded-xl text-gray-500 hover:text-gray-900 hover:bg-black/5 transition-colors",
    navLinkActive: "flex items-center gap-3 px-4 py-3 rounded-xl text-gray-900 bg-green-500/10 border border-green-500/30",
    navIcon: "size-5",
    navText: "font-medium",
    mainContent: "flex-1 overflow-y-auto",
    contentWrapper: "p-8",
    pageTitle: "text-3xl font-bold text-gray-900 mb-6",
    pageDescription: "text-gray-500",
    // Subscription page styles
    subscriptionGrid: "grid md:grid-cols-3 gap-6 max-w-5xl",
    subscriptionCard: "relative p-6 rounded-xl border backdrop-blur",
    subscriptionCardPopular: "border-green-500/50 bg-green-50/80",
    subscriptionCardNormal: "border-black/10 bg-white/80",
    subscriptionBadge: "absolute -top-3 left-1/2 -translate-x-1/2 px-3 py-1 bg-green-600 rounded-md text-xs text-white",
    subscriptionPlanName: "text-lg font-semibold text-gray-900 mb-2",
    subscriptionPriceContainer: "flex items-end gap-3 mb-2",
    subscriptionPrice: "text-3xl font-extrabold text-gray-900",
    subscriptionCredits: "text-sm text-gray-500",
    subscriptionDesc: "text-sm text-gray-500 mb-6",
    subscriptionFeatures: "space-y-3 mb-6",
    subscriptionFeature: "flex items-center gap-3 text-sm text-gray-700",
    subscriptionFeatureIcon: "w-4 h-4 text-green-500",
};
