// Style constants for Customer pages

export const customerStyles = {
    container: "flex h-screen bg-gray-950",
    sidebar: "w-64 bg-black/50 backdrop-blur-md border-r border-white/10 flex flex-col",
    sidebarHeader: "p-6 border-b border-white/10",
    sidebarTitle: "text-xl font-bold text-white",
    sidebarNav: "flex-1 p-4",
    navList: "space-y-2",
    navItem: "block",
    navLink: "flex items-center gap-3 px-4 py-3 rounded-xl text-gray-300 hover:text-white hover:bg-white/5 transition-colors",
    navLinkActive: "flex items-center gap-3 px-4 py-3 rounded-xl text-white bg-indigo-500/20 border border-indigo-500/30",
    navIcon: "size-5",
    navText: "font-medium",
    mainContent: "flex-1 overflow-y-auto",
    contentWrapper: "p-8",
    pageTitle: "text-3xl font-bold text-white mb-6",
    pageDescription: "text-gray-400",
    // Subscription page styles
    subscriptionGrid: "grid md:grid-cols-3 gap-6 max-w-5xl",
    subscriptionCard: "relative p-6 rounded-xl border backdrop-blur",
    subscriptionCardPopular: "border-indigo-500/50 bg-indigo-900/30",
    subscriptionCardNormal: "border-white/8 bg-indigo-950/30",
    subscriptionBadge: "absolute -top-3 left-1/2 -translate-x-1/2 px-3 py-1 bg-indigo-600 rounded-md text-xs text-white",
    subscriptionPlanName: "text-lg font-semibold text-white mb-2",
    subscriptionPriceContainer: "flex items-end gap-3 mb-2",
    subscriptionPrice: "text-3xl font-extrabold text-white",
    subscriptionCredits: "text-sm text-gray-400",
    subscriptionDesc: "text-sm text-gray-300 mb-6",
    subscriptionFeatures: "space-y-3 mb-6",
    subscriptionFeature: "flex items-center gap-3 text-sm text-gray-300",
    subscriptionFeatureIcon: "w-4 h-4 text-indigo-400",
};
